# Generated by Django 4.1.2 on 2022-12-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_lower',
            field=models.CharField(default=1, editable=False, max_length=255, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
