# Generated by Django 4.1.2 on 2022-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_title_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_lower',
            field=models.CharField(max_length=255, verbose_name='Наименование товара_нижний регистр'),
        ),
    ]
