# Generated by Django 4.1.2 on 2022-12-11 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_title_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_lower',
            field=models.CharField(max_length=255, verbose_name='Наим.товара в нижнем регистре_не изменять!'),
        ),
        migrations.CreateModel(
            name='HowToOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=10, verbose_name='Номер блока информации')),
                ('describe_order', models.CharField(max_length=1000, verbose_name='Способы заказа')),
                ('describe_delivery', models.CharField(max_length=1000, verbose_name='Способы доставки')),
                ('published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shops', verbose_name='Магазины')),
            ],
            options={
                'verbose_name': 'Информация о доставке и способе заказа',
                'verbose_name_plural': 'Информация о доставке и способе заказа',
            },
        ),
    ]
