# Generated by Django 4.1.2 on 2022-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_title_lower_howtoorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtoorder',
            name='describe_delivery',
            field=models.TextField(verbose_name='Способы доставки'),
        ),
        migrations.AlterField(
            model_name='howtoorder',
            name='describe_order',
            field=models.TextField(verbose_name='Способы заказа'),
        ),
    ]
