# Generated by Django 4.1.2 on 2022-12-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_howtoorder_describe_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='howtoorder',
            name='shop',
        ),
        migrations.AddField(
            model_name='howtoorder',
            name='shop',
            field=models.ManyToManyField(to='shop.shops', verbose_name='Магазины'),
        ),
    ]
