# Generated by Django 4.1.2 on 2022-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_howtoorder_shop_howtoorder_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='howtoorder',
            options={},
        ),
        migrations.CreateModel(
            name='HowToPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=10, verbose_name='Номер блока информации')),
                ('describe_order', models.TextField(verbose_name='Способы оплаты')),
                ('published', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('shop', models.ManyToManyField(to='shop.shops', verbose_name='Магазины')),
            ],
        ),
    ]
