# Generated by Django 4.1.2 on 2022-12-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_howtoorder_options_howtopay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Краткое содержание обращения')),
                ('name_user', models.CharField(max_length=10, verbose_name='Наименование орг./Имя, Фамилия')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон для связи')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('describe', models.TextField(verbose_name='Текст обращения')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
