# Generated by Django 4.1.2 on 2022-12-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
