# Generated by Django 4.1.2 on 2022-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryfeature',
            name='feature_name',
            field=models.CharField(max_length=50, verbose_name='Имя характеристики для категории'),
        ),
    ]
